jwt_secret: secret
redis:
  password: password
  address: localhost:6379
  DB: 0

mongo:
  db_name: db_name
  uri: mongodb://localhost:27017

email:
  address: user@example.com
  password: password
  smtp_host: example.com
  smtp_port: 587

server:
  address: localhost:8080